# -*- coding: utf-8 -*-
"""map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vwjiw4__IrXA5N2eDIs39h9Y8GWW61KO
"""



import fileinput

with fileinput.input(files = ('file01', 'file02')) as file:
    for line in file:
      line = line.strip()
      words = line.split()

      for word in words:
         print("%s\t%s" % (word, 1))

