# -*- coding: utf-8 -*-
"""reduce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vwjiw4__IrXA5N2eDIs39h9Y8GWW61KO
"""





import sys

d = dict()


for line in sys.stdin:

    line = line.strip()
    words = line.split("\t")

 
    for word in words:
        if word in d:
     
            d[word] = d[word] + 1
        else:
         
            d[word] = 1

for key in list(d.keys()):
    print(key, ":", d[key])